## 1. 파이썬 파일 처리

In [ ]:
sample_file = 'data/sample.txt'

In [ ]:
# 파일을 open하여 전체 내용을 읽어서 출력
with open(sample_file, mode="rt")as f:
    contents = f.read()
    print(contents)

print("----- 끝 -----")

In [ ]:
# 파일을 open하고 한 줄씩 읽어서 출력하기
with open(sample_file, 'r') as f:
    lines = f.readlines()
    for line in lines:
        print(line,end="")

print("----- 끝 -----")

In [ ]:
with open(sample_file, 'r') as f:
    line = f.readline()
    while line:
        print(line, end="")
        line = f.readline()

In [ ]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옴
with open(sample_file, 'r') as f:
    for line in f:
        print(line, end="")

print("----- 끝 -----")

In [ ]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob
txt_file_pattern = "data/*.csv"
files = glob.glob(txt_file_pattern)
print(files)
for file in files:
    print(file)
    with open(file, "r") as f:
        print(f.read())

print("----- 끝 -----")

## 2. 파이썬 문자열 다루기

In [ ]:
# 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
b1.strip()

In [ ]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 ... 사람은, 큰일에도 성실하고...."
text.rstrip('.')
text.lstrip('.')
text.strip('.')

In [ ]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text.strip(".").split(",")

In [ ]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
numbers.split(". ")

## 3. 판다스로 데이터 가져오기

In [ ]:
# 판다스 설치
!pip install pandas

In [ ]:
# 연습용 sample_data.csv 로딩하기
sample_file = 'data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

In [ ]:
sample_df.to_csv('data/sample_data_copy.csv', index=False)

In [ ]:
df2 = pd.read_csv('data/sample_data_copy.csv')
df2

In [ ]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

In [ ]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기
t_df = pd.read_csv(titanic_data, sep="\t")
t_df.head()

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [ ]:
# 앞부분 확인
t_df.head()

In [ ]:
# 뒷부분 확인
t_df.tail(10)

In [ ]:
# 데이터 개수/형태 확인
t_df.shape

In [ ]:
# 데이터 구성 정보 확인하기
t_df.info()

In [ ]:
#데이터의 기본 통계치 보기
t_df.describe()

In [ ]:
# 타이타닉 데이터 구조 및 구성 확인하기
sample_df.info()

### 4-2. 컬럼명과 인덱스 정리

In [ ]:
# 데이터프레임 복사하기 (deep copy)
sample_backup_df = sample_df.copy()
sample_backup_df

In [ ]:
# 열 이름 변경하기 : 모두 소문자로 변경
# new_cols = []
# for col in sample_df.columns:
#     new_cols.append(col.lower())
sample_df.columns = [col.lower() for col in sample_df.columns]
sample_df

In [ ]:
sample_df = sample_df.rename(columns=str.lower)
sample_df

In [ ]:
sample_df = sample_df.rename(columns=str.capitalize)
sample_df

In [ ]:
# 컬럼명의 앞글자는 소문자로, 나머지는 대문자로 수정 : lambda 함수 사용

In [ ]:
sample_df = sample_backup_df.copy()
sample_df

In [ ]:
# index 확인
t_df.index

In [ ]:
t_df.head()

In [ ]:
# 행 데이터 삭제하기
drop_index = [2, 4, 152, 154]
t_df = t_df.drop(drop_index, axis=0)
t_df.head()

In [ ]:
# index를 0부터 순서대로 assign 되도록 reset하기
t_df = t_df.reset_index(drop=True)
t_df

In [ ]:
t_df = t_df.rename(columns=str.lower)
t_df.head()

In [ ]:
# 컬럼 PassengeId를 index로 설정하기
t_df = t_df.set_index('passengerid')
t_df

In [ ]:
# 현재 index (passengerid)를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df = t_df.reset_index()
t_df

### 4-3. 데이터 정렬

In [ ]:
# 'age' 기준으로 정렬
t_df = t_df.sort_values(by='age', ascending=False).head(10)
t_df

In [ ]:
# 'age' 기준으로 내림차순으로 정렬

In [ ]:
# 'age', 'pclass'를 기준으로 정렬
t_df.sort_values(by=['pclass', 'age'], ascending=False)

# pclass는 오름차순으로 정렬, age는 내림차순으로 정렬

In [ ]:
# index를 기준으로 정렬
t_df = t_df.sort_index()
t_df

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [ ]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

In [ ]:
# 행 지정 -> 슬라이싱
score_df[2:3]

In [ ]:
# 열 접근
score_df[['이름', '국어']]

In [ ]:
score_df.이름

In [ ]:
# 특정 (행,열)의 데이터 접근
score_df[:2][['이름', '국어']]

In [ ]:
score_df

In [ ]:
# 인덱서 이용 : 레이블(이름) 인덱서
# 행 접근
score_df.loc[1]

In [ ]:
# 열 접근
score_df.loc[:,['국어', '이름']]

In [ ]:
# (행,열) 접근
score_df.loc[:1,'이름' : '국어']

In [ ]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[:1]

In [ ]:
# 열 접근
score_df.iloc[:,1:3]

In [ ]:
# (행,열) 접근
score_df.iloc[:2, 1:3]

In [ ]:
score_df

In [ ]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df.수학 >= 90]

In [ ]:
score_df[(score_df.국어 >= 90) & (score_df.수학 >= 90)]

In [ ]:
score_df[score_df.이름.isin(['정약용', '이순신'])]

In [ ]:
# 인덱서 방식으로 행 추출
score_df.loc[score_df.수학 >= 90]

In [ ]:
# (행,열) 데이터 추출
score_df.loc[score_df.수학 >= 90, ['이름', '수학']]

In [ ]:
# 열 데이터에 조건 지정
score_df.loc[:, score_df.columns != '영어']

In [ ]:
score_df.loc[:,score_df.dtypes == 'int']

### 교재 타이타닉 실습하기 171p ~ 182p

In [ ]:
# 행 데이터 가져오기
# 데이터프레임 뒤에 [ ] 오는건 괄호 안에 이름(' ')이 오면 열을 반환, : (슬라이스 연산자)가 오면 행을 반환함
# 때문에 : 가 없으면 열이기 때문에 [1]처럼 하나만 자르려 해도 [1:2]처럼 : 을 사용해야함
# 반대로 : 가 없어도 [1]처럼 열 이름(' ')이 아니라면(1 <- 정수임) 오류
t_df[0:5] # 첨부터 4까지 행만 출력
t_df[0:1] # 처음 행만 출력
t_df[::3] # 첨부터 끝까지 3단위로 출력
t_df[::-1] # 첨부터 끝까지 뒤에서 부터 출력
# 책에 4가지 설정 한꺼번에 적용되었단거는 이 결과가 4개 모두 적용한게 아니라 걍 한번에 실행했다는거(1, 2, 3 결과는 모름, 아래 결과는 4번 하나의 결과)

In [ ]:
# 열 데이터 가져오기
# 열은 하나만 자르면 시리즈로 반환, 2개 이상은 데이터프레임
# 이거도 아래의 이름으로 가져오는거랑 같음, 저렇게 하면 0번째 열의 이름(passengerid)을 가져와서 t_df['passengerid']를 실행한것과 같음
# 만약 t_df[t_df.columns[0][0:5]] 처럼 쓸 수 있는데 이건 가져온 'passengerid' 이 문자열을 0:5 로 자른거라 결국엔 t_df['pass']가 돼서 없는 열이기 때문에 오류남
len(t_df.columns) # 12, 열 이름들 배열로 받고 그 배열 길이 구함
# t_df[12] -> 이름이 아니라 인덱스로 출력할거면 아래처럼 해야함, (나중에 loc, iloc 사용하면 가능)
t_df[t_df.columns[0]] # 첫번째 열 하나만 넣음, t_df[' ']
t_df[t_df.columns[-1]] # 마지막열 출력

# 이름으로 가져오기
age = t_df['age']
print(type(age))
t_df['age'] # 이거랑
t_df.age    # 이거 둘 다 결과 같음, 하나만 할거면 . 으로도 가능, 괄호도 하나만 가능하지만 2개 이상은 [[' ', ' ']] 처럼 [] 하나 더 써야함

# 여러개 가져오기
t_df[['pclass', 'name', 'sex']]
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]]

# 이름과 인덱스 같이 쓰기
print(t_df[t_df.columns[5]][0]) # age 열을 가져와서 그 열의 첫번째(0) 값 출력, 열을 가져온 순간 데이터가 시리즈라 인덱스로 행 가져오기 가능
print(t_df['age'][0])           # 이거도 결과 같음
type(t_df[t_df.columns[0]][0]) # 타입 출력

# 같이 쓰는데 인덱스에 범위 사용 가능
t_df[t_df.columns[5]][0:5] # :: 나 -1 로 역순 출력 같은거 다 사용 가능
                           # 여기선 : 를 꼭 사용할 필요는 없지만 -1 같은 음수인덱스는 해당 데이터의 열 인덱스를 정수로하면 안됨(별도로 -1이라는 인덱스를 만들었으면 괜찮음)
                           # 열 인덱스를 별도로 만들지 않았으면 자동으로 0 1 2.. 이렇게 들어감
                           # 시리즈랑 데이터프레임 둘 다 위치인덱스랑 이름인덱스 모두 지원하는데 : 없이 숫자만 적으면 이름인덱스를 우선해서 찾음
                           # 그냥 1, 2, 3 같은애들 넣었을땐 차피 위치인덱스랑 이름인덱스 모두 같아서 상관없었는데(이름이 1, 2, 3인 행을 찾은거임)
                           # -1같은 음수인덱스는 실제 위치인덱스에는 없는 인덱스이므로 자동 생성되지 않기 때문에 -1이란 이름을 찾을 수 없어 오류남

# 전부다 합친거
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]][2:15:3] # 열 인덱스로 이름 가져와서 열 여러개 가져온 후 2행 부터 14행 까지 3단위로 가져옴

In [ ]:
# loc 을 사용해 이름 인덱스로 슬라이싱하기, 행, 열 둘 다 가능
# loc 은 완전히 이름 인덱스를 사용하며, 이름에 슬라이싱 연산자 사용 가능 [ s : s : s ], ([행], [행, 열])
# 인덱스의 이름이 1, 2, 'A', 'ㅁㄴㅇㄹ', 132 이런식이라면 1:'A' , :: , :'ㅁㄴㅇㄹ' 이런거 가능, 얘는 1부터 'A' 전까지가 아닌 그냥 쓰는대로 다 포함, 스텝은 숫자만

# 현재 사용중인 타이타닉 데이터의 인덱스는 자동생성 정수 인덱스이기 때문에 표기는 같지만 아래 iloc과 작동은 다름
t_df.loc[0] # 첫 행 출력, loc은 단일 행도 : 없이 가능
t_df.loc[0:5] # 0부터 5행까지 6개의 행 출력, (loc은 다 포함)
t_df.loc[0:10:2] # 2단위로

t_df.loc[:,'age'] # 행은 전부다, 열은 'age'만 출력
t_df.loc[:, ['age', 'sex']] # 행 전부, 열 두 개, loc 도 여러개를 배열로 가져오기 가능
t_df.loc[2:5, 'survived':'age'] # 행 2부터 5까지, 열 'survived' 부터 'age' 까지, 슬라이싱은 2개 이상이어도 괄호 필요없음

# iloc 을 사용해 위치 인덱스로 슬라이싱하기, 행, 열 둘 다 가능, loc과 전부다 똑같은데 사용하는 인덱스랑 포함 범위가 다름, 얘는 스탑 전까지임
# 이거처럼 위 loc과 똑같이 써도 loc은 이름을 따라가고 iloc은 인덱스 위치를 따라감, 만약 인덱스가 ㅁ,ㄴ,ㅇ,ㄹ 이런식이라면 loc은 표기가 달라짐
# iloc은 어차피 위치 인덱스를 쓰기 때문에 안바꿔도 됨
t_df.iloc[0]
t_df.iloc[0:5]
t_df.iloc[0:10:2]
# iloc은 열도 이름 대신 위치 인덱스로 씀, 눈으론 안보임, 대충 순서대로
t_df.iloc[:, [0, 2]]
t_df.iloc[1:5, 1:4]

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [ ]:
sample_file = 'data/sales_sample.csv'

In [ ]:
# 샘플 파일 로딩
import pandas as pd
sales_df = pd.read_csv(sample_file)
sales_df

In [ ]:
# 지역별 판매 기록의 개수
sales_df['지역'].value_counts()

In [ ]:
# 상품별 판매 기록의 개수와 비율
sales_df['상품'].value_counts()

In [ ]:
sales_df['상품'].value_counts(normalize=True)

In [ ]:
# 지역과 상품의 조합별 판매 기록 개수
sales_df.value_counts(['지역', '상품'])

In [ ]:
sample_df = pd.read_csv('data/sample_data.csv')
sample_df

In [ ]:
sample_df['City'].value_counts(dropna=False, ascending=True)

In [ ]:
# 지역별 총매출
sales_df.groupby(by='지역')['매출'].sum()

In [ ]:
# 상품별 평균 매출 -> 상품을 기준으로 매출의 평균
sales_df.groupby(by='상품')['매출'].mean()

In [ ]:
# 지역별 판매수량의 합계와 매출의 합계 -> 지역 기준으로 판매수량과 매출의 각각의 합계
sales_df.groupby(by='지역', as_index=False)[['판매수량', '매출']].sum()

In [ ]:
# 지역과 상품별 평균 매출 -> 지역과 상품 기준으로 매출의 평균
sales_df.groupby(by=['지역', '상품'])['매출'].mean()

In [ ]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시
sales_df.pivot_table(
    index='상품',
    columns='지역',
    values='매출',
    aggfunc='sum',
    margins=True
)

In [ ]:
# 지역별 매출 : 건수, 합계, 평균
sales_df.groupby(by='지역')['매출'].agg(['count', 'sum', 'mean', 'max'])

## 5-1. 결측치 처리

In [33]:
import pandas as pd
sample_df = pd.read_csv('data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [2]:
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 356.0 bytes

In [ ]:
# isna
sample_df.isna().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [ ]:
# isnull
sample_df.isnull().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [11]:
# 결측치가 있는 데이터 확인
# 'Age' 컬럼에 결측치가 있는지와 결측치 데이터 확인
print(sample_df['Age'].isna().sum())
sample_df[sample_df['Age'].isna()]

2

     Name  Age Gender         City
1     Bob  NaN      M  Los Angeles
4  Edward  NaN      M      Houston

In [16]:
# 어떤 컬럼에든 결측치가 있는 데이터의 갯수, 데이터 확인
na_df = sample_df[sample_df.isna().any(axis=1)]
print(len(na_df))
na_df

3

      Name   Age Gender         City
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
4   Edward   NaN      M      Houston

In [21]:
# 결측치가 있는 데이터 삭제 : dropna
# City에 결측치가 있는 경우 데이터 삭제
sample_df = sample_df.dropna(subset='City')

In [22]:
sample_df

     Name   Age Gender         City
0   Alice  24.0      F     New York
1     Bob   NaN      M  Los Angeles
3   David  29.0      M      Chicago
4  Edward   NaN      M      Houston
5   Alice  24.0      F     New York
6   Susan  32.0      F      Houston

In [32]:
# Age 결측치는 Age의 평균값으로 채우기
age_avg = sample_df['Age'].mean()
sample_df['Age'] = sample_df['Age'].fillna(sample_df['Age'].mean())
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

## 5-2. 중복치 처리

In [38]:
# 중복값 확인
sample_df.duplicated().sum()

np.int64(1)

In [40]:
# 중복값이 데이터 확인
sample_df[sample_df.duplicated()]

    Name   Age Gender      City
5  Alice  24.0      F  New York

In [42]:
# 중복값 삭제
sample_df = sample_df.drop_duplicates()
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
6    Susan  32.0      F      Houston