## 1. 파이썬 파일 처리

In [1]:
sample_file = 'data/sample.txt'

In [2]:
# 파일을 open하여 전체 내용을 읽어서 출력
with open(sample_file, mode="rt")as f:
    contents = f.read()
    print(contents)

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

----- 끝 -----

In [4]:
# 파일을 open하고 한 줄씩 읽어서 출력하기
with open(sample_file, 'r') as f:
    lines = f.readlines()
    for line in lines:
        print(line,end="")

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [5]:
with open(sample_file, 'r') as f:
    line = f.readline()
    while line:
        print(line, end="")
        line = f.readline()

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

In [ ]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옴
with open(sample_file, 'r') as f:
    for line in f:
        print(line, end="")

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [8]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob
txt_file_pattern = "data/*.csv"
files = glob.glob(txt_file_pattern)
print(files)
for file in files:
    print(file)
    with open(file, "r") as f:
        print(f.read())

print("----- 끝 -----")

['data\\sales_sample.csv', 'data\\sample_data.csv']
data\sales_sample.csv
지역,상품,판매수량,매출
서울,노트북,2,120
서울,태블릿,1,80
부산,노트북,2,100
부산,태블릿,1,70
서울,노트북,3,150
부산,노트북,1,110
대전,노트북,2,130
대전,태블릿,2,90
서울,태블릿,2,160
부산,태블릿,3,210
대전,노트북,1,65
대전,태블릿,1,45
서울,노트북,1,60
부산,노트북,3,150
대전,노트북,2,120
서울,태블릿,2,160
부산,태블릿,1,70
대전,태블릿,3,135
서울,노트북,2,120
부산,태블릿,2,140

data\sample_data.csv
Name,Age,Gender,City
Alice,24.0,F,New York
Bob,,M,Los Angeles
Charlie,22.0,M,
David,29.0,M,Chicago
Edward,,M,Houston
Alice,24.0,F,New York
Susan,32.0,F,Houston

----- 끝 -----

## 2. 파이썬 문자열 다루기

In [9]:
# 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
b1.strip()

'작은 일에 성실한 사람은      큰일에도 성실하고'

In [14]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 ... 사람은, 큰일에도 성실하고...."
text.rstrip('.')
text.lstrip('.')
text.strip('.')

'작은 일에 성실한 ... 사람은, 큰일에도 성실하고'

In [16]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text.strip(".").split(",")

['작은 일에 성실한 사람은', ' 큰일에도 성실하고']

In [18]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
numbers.split(". ")

['1', '2', '3', '4', '5', '6']

## 3. 판다스로 데이터 가져오기

In [19]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in c:\Users\USER\anaconda3\envs\PyData26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\USER\anaconda3\envs\PyData26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\USER\anaconda3\envs\PyData26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\USER\anaconda3\envs\PyData26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\USER\anaconda3\envs\PyData26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [20]:
# 연습용 sample_data.csv 로딩하기
sample_file = 'data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [24]:
sample_df.to_csv('data/sample_data_copy.csv', index=False)

In [ ]:
df2 = pd.read_csv('data/sample_data_copy.csv')
df2

          Age Gender         City
Name
Alice    24.0      F     New York
Bob       NaN      M  Los Angeles
Charlie  22.0      M          NaN
David    29.0      M      Chicago
Edward    NaN      M      Houston
Alice    24.0      F     New York
Susan    32.0      F      Houston

In [27]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

In [30]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기
t_df = pd.read_csv(titanic_data, sep="\t")
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [31]:
# 앞부분 확인
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [33]:
# 뒷부분 확인
t_df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
146,147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.0,0,0,350043,7.7958,NaN,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,NaN,S
148,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26.0000,F2,S
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [34]:
# 데이터 개수/형태 확인
t_df.shape

(156, 12)

In [35]:
# 데이터 구성 정보 확인하기
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [36]:
#데이터의 기본 통계치 보기
t_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [38]:
# 타이타닉 데이터 구조 및 구성 확인하기
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 356.0 bytes

### 4-2. 컬럼명과 인덱스 정리

In [39]:
# 데이터프레임 복사하기 (deep copy)
sample_backup_df = sample_df.copy()
sample_backup_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
# 열 이름 변경하기 : 모두 소문자로 변경
# new_cols = []
# for col in sample_df.columns:
#     new_cols.append(col.lower())
sample_df.columns = [col.lower() for col in sample_df.columns]
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [44]:
sample_df = sample_df.rename(columns=str.lower)
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [45]:
sample_df = sample_df.rename(columns=str.capitalize)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
# 컬럼명의 앞글자는 소문자로, 나머지는 대문자로 수정 : lambda 함수 사용

In [46]:
sample_df = sample_backup_df.copy()
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [48]:
# index 확인
t_df.index

RangeIndex(start=0, stop=156, step=1)

In [49]:
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [50]:
# 행 데이터 삭제하기
drop_index = [2, 4, 152, 154]
t_df = t_df.drop(drop_index, axis=0)
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [54]:
# index를 0부터 순서대로 assign 되도록 reset하기
t_df = t_df.reset_index(drop=True)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [56]:
t_df = t_df.rename(columns=str.lower)
t_df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [58]:
# 컬럼 PassengeId를 index로 설정하기
t_df = t_df.set_index('passengerid')
t_df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...
150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [60]:
# 현재 index (passengerid)를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df = t_df.reset_index()
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-3. 데이터 정렬

In [ ]:
# 'age' 기준으로 정렬
t_df = t_df.sort_values(by='age', ascending=False).head(10)
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
31,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
122,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [ ]:
# 'age' 기준으로 내림차순으로 정렬

In [ ]:
# 'age', 'pclass'를 기준으로 정렬
t_df.sort_values(by=['pclass', 'age'], ascending=False)

# pclass는 오름차순으로 정렬, age는 내림차순으로 정렬

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
130,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,NaN,S
127,130,0,3,"Ekstrom, Mr. Johan",male,45.0,0,0,347061,6.9750,NaN,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
25,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
134,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S
29,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
53,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
62,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C

In [69]:
# index를 기준으로 정렬
t_df = t_df.sort_index()
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [70]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [71]:
# 행 지정 -> 슬라이싱
score_df[2:3]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [74]:
# 열 접근
score_df[['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [75]:
score_df.이름

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [79]:
# 특정 (행,열)의 데이터 접근
score_df[:2][['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100

In [80]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [81]:
# 인덱서 이용 : 레이블(이름) 인덱서
# 행 접근
score_df.loc[1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [83]:
# 열 접근
score_df.loc[:,['국어', '이름']]

    국어   이름
0   70  정약용
1  100  이순신
2   90  이율곡
3   85  홍길동

In [88]:
# (행,열) 접근
score_df.loc[:1,'이름' : '국어']

    이름   국어
0  정약용   70
1  이순신  100

In [90]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[:1]

    이름  국어  영어   수학
0  정약용  70  80  100

In [92]:
# 열 접근
score_df.iloc[:,1:3]

    국어   영어
0   70   80
1  100   80
2   90   95
3   85  100

In [93]:
# (행,열) 접근
score_df.iloc[:2, 1:3]

    국어  영어
0   70  80
1  100  80

In [94]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [ ]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [96]:
score_df[(score_df.국어 >= 90) & (score_df.수학 >= 90)]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [97]:
score_df[score_df.이름.isin(['정약용', '이순신'])]

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70

In [98]:
# 인덱서 방식으로 행 추출
score_df.loc[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [99]:
# (행,열) 데이터 추출
score_df.loc[score_df.수학 >= 90, ['이름', '수학']]

    이름   수학
0  정약용  100
2  이율곡   90
3  홍길동   90

In [100]:
# 열 데이터에 조건 지정
score_df.loc[:, score_df.columns != '영어']

    이름   국어   수학
0  정약용   70  100
1  이순신  100   70
2  이율곡   90   90
3  홍길동   85   90

In [101]:
score_df.loc[:,score_df.dtypes == 'int']

    국어   영어   수학
0   70   80  100
1  100   80   70
2   90   95   90
3   85  100   90

### 교재 타이타닉 실습하기 171p ~ 182p

In [ ]:
# 행 데이터 가져오기
# 데이터프레임 뒤에 [ ] 오는건 괄호 안에 이름(' ')이 오면 열을 반환, : (슬라이스 연산자)가 오면 행을 반환함
# 때문에 : 가 없으면 열이기 때문에 [1]처럼 하나만 자르려 해도 [1:2]처럼 : 을 사용해야함
# 반대로 : 가 없어도 [1]처럼 열 이름(' ')이 아니라면(1 <- 정수임) 오류
t_df[0:5] # 첨부터 4까지 행만 출력
t_df[0:1] # 처음 행만 출력
t_df[::3] # 첨부터 끝까지 3단위로 출력
t_df[::-1] # 첨부터 끝까지 뒤에서 부터 출력
# 책에 4가지 설정 한꺼번에 적용되었단거는 이 결과가 4개 모두 적용한게 아니라 걍 한번에 실행했다는거(1, 2, 3 결과는 모름, 아래 결과는 4번 하나의 결과)

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [ ]:
# 열 데이터 가져오기
# 열은 하나만 자르면 시리즈로 반환, 2개 이상은 데이터프레임
# 이거도 아래의 이름으로 가져오는거랑 같음, 저렇게 하면 0번째 열의 이름(passengerid)을 가져와서 t_df['passengerid']를 실행한것과 같음
# 만약 t_df[t_df.columns[0][0:5]] 처럼 쓸 수 있는데 이건 가져온 'passengerid' 이 문자열을 0:5 로 자른거라 결국인 t_df['pass']가 돼서 없는 열이기 때문에 오류남
len(t_df.columns) # 12, 열 이름들 배열로 받고 그 배열 길이 구함
# t_df[12] -> 이름이 아니라 인덱스로 출력할거면 아래처럼 해야함, (나중에 loc, iloc 사용하면 가능)
t_df[t_df.columns[0]] # 첫번째 열 하나만 넣음, t_df[' ']
t_df[t_df.columns[-1]] # 마지막열 출력

# 이름으로 가져오기
age = t_df['age']
print(type(age))
t_df['age'] # 이거랑
t_df.age    # 이거 둘 다 결과 같음, 하나만 할거면 . 으로도 가능, 괄호도 하나만 가능하지만 2개 이상은 [[' ', ' ']] 처럼 [] 하나 더 써야함

# 여러개 가져오기
t_df[['pclass', 'name', 'sex']]
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]]

# 이름과 인덱스 같이 쓰기
print(t_df[t_df.columns[5]][0]) # age 열을 가져와서 그 열의 첫번째(0) 값 출력, 열을 가져온 순간 데이터가 시리즈라 인덱스로 행 가져오기 가능
print(t_df['age'][0])           # 이거도 결과 같음
type(t_df[t_df.columns[0]][0]) # 타입 출력

# 같이 쓰는데 인덱스에 범위 사용 가능
t_df[t_df.columns[5]][0:5] # :: 나 -1 로 역순 출력 같은거 다 사용 가능
                           # 여기선 : 를 꼭 사용할 필요는 없지만 -1 같은 음수인덱스는 해당 데이터의 열 인덱스를 정수로하면 안됨(별도로 -1이라는 인덱스를 만들었으면 괜찮음)
                           # 열 인덱스를 별도로 만들지 않았으면 자동으로 0 1 2.. 이렇게 들어감
                           # 시리즈랑 데이터프레임 둘 다 위치인덱스랑 이름인덱스 모두 지원하는데 : 없이 숫자만 적으면 이름인덱스를 우선해서 찾음
                           # 그냥 1, 2, 3 같은애들 넣었을땐 차피 위치인덱스랑 이름인덱스 모두 같아서 상관없었는데(이름이 1, 2, 3인 행을 찾은거임)
                           # -1같은 음수인덱스는 실제 위치인덱스에는 없는 인덱스이므로 자동 생성되지 않기 때문에 -1이란 이름을 찾을 수 없어 오류남

# 전부다 합친거
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]][2:15:3] # 열 인덱스로 이름 가져와서 열 여러개 가져온 후 2행 부터 14행 까지 3단위로 가져옴

<class 'pandas.Series'>
22.0
22.0

    pclass                                          name     sex
2        1  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5        3                Palsson, Master. Gosta Leonard    male
8        3               Sandstrom, Miss. Marguerite Rut  female
11       3                   Andersson, Mr. Anders Johan    male
14       3                          Rice, Master. Eugene    male

In [ ]:
# loc 을 사용해 이름 인덱스로 슬라이싱하기, 행, 열 둘 다 가능
# loc 은 완전히 이름 인덱스를 사용하며, 이름에 슬라이싱 연산자 사용 가능 [ s : s : s ], ([행], [행, 열])
# 인덱스의 이름이 1, 2, 'A', 'ㅁㄴㅇㄹ', 132 이런식이라면 1:'A' , :: , :'ㅁㄴㅇㄹ' 이런거 가능, 얘는 1부터 'A' 전까지가 아닌 그냥 쓰는대로 다 포함, 스텝은 숫자만

# 현재 사용중인 타이타닉 데이터의 인덱스는 자동생성 정수 인덱스이기 때문에 표기는 같지만 아래 iloc과 작동은 다름
t_df.loc[0] # 첫 행 출력, loc은 단일 행도 : 없이 가능
t_df.loc[0:5] # 0부터 5행까지 6개의 행 출력, (loc은 다 포함)
t_df.loc[0:10:2] # 2단위로

t_df.loc[:,'age'] # 행은 전부다, 열은 'age'만 출력
t_df.loc[:, ['age', 'sex']] # 행 전부, 열 두 개, loc 도 여러개를 배열로 가져오기 가능
t_df.loc[2:5, 'survived':'age'] # 행 2부터 5까지, 열 'survived' 부터 'age' 까지, 슬라이싱은 2개 이상이어도 괄호 필요없음

# iloc 을 사용해 위치 인덱스로 슬라이싱하기, 행, 열 둘 다 가능, loc과 전부다 똑같은데 사용하는 인덱스랑 포함 범위가 다름, 얘는 스탑 전까지임
# 이거처럼 위 loc과 똑같이 써도 loc은 이름을 따라가고 iloc은 인덱스 위치를 따라감, 만약 인덱스가 ㅁ,ㄴ,ㅇ,ㄹ 이런식이라면 loc은 표기가 달라짐
# iloc은 어차피 위치 인덱스를 쓰기 때문에 안바꿔도 됨
t_df.iloc[0]
t_df.iloc[0:5]
t_df.iloc[0:10:2]
# iloc은 열도 이름 대신 위치 인덱스로 씀, 눈으론 안보임, 대충 순서대로
t_df.iloc[:, [0, 2]]
t_df.iloc[1:5, 1:4]

   survived  pclass                                               name
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
3         0       3                                   Moran, Mr. James
4         0       1                            McCarthy, Mr. Timothy J

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [ ]:
sample_file = 'data/sales_sample.csv'

In [ ]:
# 샘플 파일 로딩

In [ ]:
# 지역별 판매 기록의 개수

In [ ]:
# 상품별 판매 기록의 개수와 비율

In [ ]:
# 지역과 상품의 조합별 판매 기록 개수

In [ ]:
# 지역별 총매출

In [ ]:
# 상품별 평균 매출

In [ ]:
# 지역별 판매수량의 합계와 매출의 합계

In [ ]:
# 지역과 상품별 평균 매출

In [ ]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시